version: '3.8'

services:
  web:
    labels:
        shipyard.route: '/'
    build:
      context: ./web
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=testco
      - DATABASE_PASSWORD=development
      - DATABASE_NAME=postgres
    networks:
      - custom_network

  db:
    image: "postgres:12-3.1"
    environment:
      POSTGRES_USER: testco
      POSTGRES_PASSWORD: development
      POSTGRES_DB: postgres
    ports:
      - "5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - non_existent_network  # An undefined network to trigger an error

networks:
  custom_network:
    driver: bridge