version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydb

  db:
    image: "postgres:111.6-alpine"  # Non-existent PostgreSQL version
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5434:5434"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

